### ISSUE TITLE
图挂了

### ISSUE THREAD

**Issue by DrawGu** [CodyyAndroid/CodyyChart#1]
图挂了

**Comment by EHG613** [comment]
请联系@jdpxiaoming 维护




在2019年01月29日 17:36，JiajiaGu 写道：

图挂了

**Comment by EHG613** [comment]
@jdpxiaoming

**Comment by jdpxiaoming** [comment]
I am sorry for the thing. feel free , I prepare to restore it now .

**Comment by jdpxiaoming** [comment]
fix it .
